---
output: github_document
always_allow_html: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# About the Paper
First Test Entry.


```{r message=FALSE, warning=FALSE, echo=FALSE}
library(DT)
library(tidyverse)
library(kableExtra)
con <- readr::read_rds("0_data/cls_tp_final.rds") %>%
  dplyr::select(cid, concept_name, tid, term, cat1, cat2, cat3, size, avg_ngram, avg_sim, complex_score) %>%
  dplyr::arrange(cid) %>%
  dplyr::filter(cid %in% 1:100)
openxlsx::write.xlsx(con, "2_output/concept_list.xlsx", TRUE, TRUE)

ter <- readr::read_rds("0_data/tls_tp_final.rds") %>%
  dplyr::select(tid, term, term_raw, cat1, cat2, cat3) %>%
  dplyr::arrange(tid) %>%
  dplyr::filter(tid %in% 1:1000)
openxlsx::write.xlsx(ter, "2_output/term_list.xlsx", TRUE, TRUE)
```

# Concept List
The table below shows the first 100 concepts from the concept list proposed in the paper:

"The Standardization of Accounting Language"

<a href="2_output/concept_list.xlsx" download="2_output/concept_list.xlsx">download concept list</a>
```{r message=FALSE, warning=FALSE, echo=FALSE}
con %>%
  dplyr::mutate(dplyr::across(where(is.character), ~ dplyr::if_else(is.na(.), "", .))) %>%
  slice(1:10) %>%
  knitr::kable() %>%
  kableExtra::kable_paper() %>%
  kable_styling(font_size = 11)
```


# Term List
The table below shows the first 1,000 terms from the term list proposed in the paper:

"The Standardization of Accounting Language"

```{r message=FALSE, warning=FALSE, echo=FALSE}
ter %>%
  dplyr::mutate(dplyr::across(where(is.character), ~ dplyr::if_else(is.na(.), "", .))) %>%
  slice(1:10) %>%
  knitr::kable() %>%
  kableExtra::kable_paper() %>%
  kable_styling(font_size = 11)

```


